#!/bin/bash
# Script that is called by the www server as user sentinel (from php.)
# Resets to latest sentinel master from GitHub and cabal installs it.

# NOTE: to allow the www server to execute this script as sentinel,
# add the following line (without #) to the sudoers file with: sudo visudo 
#www-data ALL=(sentinel) NOPASSWD: /home/sentinel/git/sentinel/scripts/phpCompileSentinel

echo Running phpCompileSentinel

# set path and env
HOME="/home/sentinel"
LANG=en_US.UTF-8
PATH=/home/sentinel/git/sentinel/scripts:/home/sentinel/.cabal/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

export HOME
export LANG
export PATH

killall --quiet sentinel

cd /home/sentinel/git/sentinel
echo Sentinel is on branch `git rev-parse --abbrev-ref HEAD`
echo Resetting to latest commit on master
git fetch --prune

git checkout --track origin/master
# this may fail if master already exists, in which case no checkout is done, so we need another git checkout:
git checkout master

git reset origin --hard

echo "Cleaning Sentinel and installing sandbox (if not already installed)"

cabal clean 
rm -rf .cabal-sandbox
cabal sandbox init

echo Running cabal update and cabal install on sentinel
cabal update
cabal install --bindir=/home/sentinel/.cabal/bin/
